module.exports = {
  channels: {
    APP_INFO: 'app_info',
    AUTH_LOGIN: 'auth_login',
    AUTH_REGISTER: 'auth_register',
    AUTH_VERIFY_TOKEN: 'auth_verify_token',
    DELETE_CONNECTION: 'delete-connection',
    ADD_CONNECTION: 'add-connection',
    CREATE_DB: 'create-database',
    LOAD_DB: 'load-database',
    GET_DB: 'get-full-data',
    SHARE_DB: 'share-database',
    UPDATE_LANGUAGE: 'update-language',
    UPDATE_THEME: 'update-theme',
    CHECK_LICENSE: 'check-license',
    SET_TRIAL: 'set-trial',
    UPDATE_KEY: 'update-key',
    GET_ALL_TABLES: 'get-all-tables',
    GET_TABLE_RELATIONS: 'get-table-relations',
    DELETE_TABLE: 'delete-table',
    GET_TABLE: 'get-table',
    ADD_TABLE: 'add-table',
    RENAME_TABLE: 'rename-table',
    UPDATE_QUERY: 'update-table-query',
    GET_TABLE_SIZE: 'get-table-size',
    LOAD_QUERY: 'load-result',
    SAVE_QUERY: 'save-result',
    TEST_QUERY: 'test-query',
    GET_TABLE_COLUMNS: 'get-table-columns',
    RENAME_CONNECTION: 'rename-connection',
    UPDATE_DEFAULT_TABLE_ROW: 'update-default-table-row',
    DELETE_DEFAULT_TABLE_ROW: 'delete-default-table-row',
    SEARCH_BY_ALL_TABLES: 'search-by-all-tables',
  },
};
